# Generated by Django 6.0.1 on 2026-01-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='favorite_post',
        ),
    ]
